on: 
  workflow_call:
    inputs:
      app-context-path: 
        required: true
        type: string
      base-image-name:
        required: true
        type: string
      target-image-name:
        required: true
        type: string

jobs:
  build-and-publish:
    name: Build & publish container image
    runs-on: ubuntu-latest
    needs: [get-latest-tag]
    steps:
      - name: Download package version artifact
        uses: actions/download-artifact@v2
        with:
          name: package-version

      - name: Package version to output and as an environment variable
        id: package-version-to-output
        run: |
          PACKAGE_VERSION=`cat latest-version.txt`
          echo $PACKAGE_VERSION
          echo ::set-output name=PACKAGE_VERSION::$(echo ${PACKAGE_VERSION})

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: ${{ app-context-path }}
          platforms: linux/amd64
          load: true
          build-args: |
            BASE_IMAGE=${{ inputs.base-image-name }}:${{ steps.package-version-to-output.outputs.PACKAGE_VERSION }}
          tags: "${{ inputs.target-image-name }}:${{ steps.package-version-to-output.outputs.PACKAGE_VERSION }}"

      - name: Run Trivy config scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "${{ app-context-path }}"
          hide-progress: false
          format: "sarif"
          output: "trivy-config-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ inputs.target-image-name }}:${{ steps.package-version-to-output.outputs.PACKAGE_VERSION }}"
          format: "sarif"
          output: "trivy-image-results.sarif"
          severity: "CRITICAL,HIGH"
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "./"

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ app-context-path }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BASE_IMAGE=${{ inputs.base-image-name }}:${{ steps.package-version-to-output.outputs.PACKAGE_VERSION }}
          tags: "${{ inputs.target-image-name }}:${{ steps.package-version-to-output.outputs.PACKAGE_VERSION }}"