name: Create and push latest lazylibrarian image

on:
  schedule:
     - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  get-latest-tag:
    uses: ./.github/workflows/get-latest-tag.yaml
    with: 
      script-name: 'check-new-version-lazylibrarian.sh'

  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      app-context-path: ./lazylibrarian-with-calibre
      base-image-name: docker.io/linuxserver/lazylibrarian
      target-image-name: ghcr.io/arsenikki/lazylibrarian